name: flutter_slidable
description: A Flutter implementation of slidable list item with directional slide actions that can be dismissed.
version: 2.1.0
publish_to: "none"
homepage: https://github.com/sunderee/flutter_slidable

environment:
  sdk: ">=2.19.4"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # Linter
  flutter_lints: ^2.0.1

  # Testing
  collection: ^1.17.0
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
